import puppeteer from "puppeteer-core";
const api="http://localhost:5000/api";
const r=await fetch(`${api}/auth/login`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:"admin@demo.com",password:"admin123"})});
const d=await r.json();
const b=await puppeteer.launch({executablePath:"/usr/bin/google-chrome",headless:"new",args:["--no-sandbox","--disable-gpu"]});
const p=await b.newPage();await p.setViewport({width:1440,height:900});
await p.goto("http://localhost:5173/",{waitUntil:"domcontentloaded"});
await p.evaluate((t,u)=>{localStorage.setItem("token",t);if(u)localStorage.setItem("user",JSON.stringify(u));},d.accessToken,d.user);
await p.goto("http://localhost:5173/pedidos",{waitUntil:"networkidle2"});
await new Promise(x=>setTimeout(x,1500));
await p.evaluate(()=>{const btn=[...document.querySelectorAll("button")].find(x=>x.className.includes("text-destructive"));if(btn)btn.click();});
await new Promise(x=>setTimeout(x,800));
await p.screenshot({path:"/tmp/deldialog.png"});await b.close();console.log("ok");
